logo = TextDrawCreate(635.600341, 2.337756, "Azure ~w~RP");
TextDrawLetterSize(logo, 0.346000, 1.679645);
TextDrawAlignment(logo, 3);
TextDrawColor(logo, 16777215);
TextDrawSetShadow(logo, 1);
TextDrawSetProportional(logo, 1);

speedo_bg = TextDrawCreate(241.500030, 343.000000, "LD_POOL:ball");
TextDrawLetterSize(speedo_bg, 0.000000, 0.000000);
TextDrawTextSize(speedo_bg, 159.000000, 195.000000);
TextDrawColor(speedo_bg, 0x00000099);
TextDrawFont(speedo_bg, 4);

speedo_info = TextDrawCreate(306.0, 366.613281, "Speed:~n~Fuel:~n~Health:~n~");
TextDrawLetterSize(speedo_info, 0.357598, 1.838932);
TextDrawAlignment(speedo_info, 3);
TextDrawColor(speedo_info, 0xFFFFFF99);
TextDrawSetShadow(speedo_info, 1);
TextDrawSetProportional(speedo_info, 1);